CREATE TABLE ORDERS (
  id            INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY ( START WITH 1, INCREMENT BY 1),
  customerId    INT     NOT NULL,
  salesPersonId INT     NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE USERS (
  id        INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY ( START WITH 1, INCREMENT BY 1),
  firstname VARCHAR(255),
  lastname  VARCHAR(255),
  age       INTEGER,
  PRIMARY KEY (id)
)