CREATE TABLE USERS (
  id        INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  firstname VARCHAR(20)      NOT NULL,
  lastname  VARCHAR(20)      NOT NULL,
  age       INT(10)          NOT NULL,
  PRIMARY KEY (id) USING BTREE
)
  ENGINE = InnoDB
  DEFAULT CHARSET = utf8;

CREATE TABLE ORDERS (
  id              INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  customer_id     INT(10) UNSIGNED NOT NULL,
  sales_person_id INT(10) UNSIGNED NOT NULL,
  product         VARCHAR(20)      NOT NULL,
  price           INT(10) UNSIGNED NOT NULL,
  CONSTRAINT PK_ORDERS PRIMARY KEY (id) USING BTREE,
  CONSTRAINT FK_CUSTOMER_ID FOREIGN KEY (customer_id) REFERENCES USERS (id)
    ON UPDATE CASCADE
    ON DELETE CASCADE,
  CONSTRAINT FK_SALES_PERSON_ID FOREIGN KEY (sales_person_id) REFERENCES USERS (id)
    ON UPDATE CASCADE
    ON DELETE CASCADE
)
  ENGINE = InnoDB
  DEFAULT CHARSET = utf8;
